project_id = "mrxjweoyzmanncphskxs"

[functions.send-notification]
verify_jwt = false

[functions.send-receipt]
verify_jwt = false

[functions.razorpay-subscription]
verify_jwt = false

[functions.verify-team-access]
verify_jwt = false

[functions.create-admin]
verify_jwt = true
